// ─────────────────────────────────────────────────────────────────
// Auto-generated by  VerilogEmitter
// Algebra : Cl(2,0)  (2D Euclidean Geometric Algebra)
// Bases   : scalar(0), e1(1), e2(2), e12(12)
// Metric  : e1² = e2² = +1
// Inputs  : INT8 signed  →  Outputs : INT18 signed
// Operation: C = A * B  (full geometric product)
// ─────────────────────────────────────────────────────────────────

module geometric_product_cl20 (
    input  signed [7:0] a0,
    input  signed [7:0] a1,
    input  signed [7:0] a2,
    input  signed [7:0] a12,
    input  signed [7:0] b0,
    input  signed [7:0] b1,
    input  signed [7:0] b2,
    input  signed [7:0] b12,
    output signed [17:0] c0,
    output signed [17:0] c1,
    output signed [17:0] c2,
    output signed [17:0] c12

);

    // scalar
    assign c0 = (a0 * b0) + (a1 * b1) + (a2 * b2) - (a12 * b12);

    // e1 vector
    assign c1 = (a0 * b1) + (a1 * b0) - (a2 * b12) + (a12 * b2);

    // e2 vector
    assign c2 = (a0 * b2) + (a1 * b12) + (a2 * b0) - (a12 * b1);

    // e12 bivector
    assign c12 = (a0 * b12) + (a1 * b2) - (a2 * b1) + (a12 * b0);

endmodule
