"""
VerilogEmitter
────────────────────────────────────────────────────────────────
Auto-generates combinational Verilog for the Cl(2,0) Geometric Product.

Algebra : Cl(2,0) — 2D Euclidean Geometric Algebra
Bases   : scalar(0), e1(1), e2(2), e12(12)
Metric  : e1² = e2² = +1
Inputs  : INT8  signed  (a0..a12, b0..b12)
Outputs : INT18 signed  (safe headroom: 4 products × 16-bit max)

Run:
    python verilog_emitter.py
Produces:
    geometric_product_cl20.v
────────────────────────────────────────────────────────────────
"""

# ── 1. Algebra: Cl(2,0) Basis Blades ─────────────────────────────────────────

# Each blade is a sorted tuple of generator indices.
# ()     = scalar  (grade 0)
# (1,)   = e1      (grade 1)
# (2,)   = e2      (grade 1)
# (1,2)  = e12     (grade 2)

BLADES      = [(), (1,), (2,), (1, 2)]
BLADE_LABEL = {(): "0", (1,): "1", (2,): "2", (1, 2): "12"}
BLADE_NAME  = {(): "scalar", (1,): "e1 vector", (2,): "e2 vector", (1, 2): "e12 bivector"}


# ── 2. Symbolic Blade Multiplication ─────────────────────────────────────────

def blade_product(a, b):
    """
    Geometric product of two basis blades in Cl(2,0).

    Algorithm:
      1. Concatenate index lists.
      2. Bubble-sort to canonical order, tracking sign from each swap.
      3. Contract repeated indices using metric: e_i² = +1 (sign unchanged).

    Returns:
      (sign: int ∈ {+1, -1}, result_blade: tuple)
    """
    seq  = list(a) + list(b)
    sign = 1

    # Step 1 — Bubble-sort with sign tracking
    changed = True
    while changed:
        changed = False
        for i in range(len(seq) - 1):
            if seq[i] > seq[i + 1]:
                seq[i], seq[i + 1] = seq[i + 1], seq[i]
                sign    *= -1
                changed  = True

    # Step 2 — Contract pairs: e_i² = +1, so just remove them (sign unchanged)
    contracted, i = [], 0
    while i < len(seq):
        if i + 1 < len(seq) and seq[i] == seq[i + 1]:
            i += 2          # metric = +1 → multiply sign by 1 (no-op)
        else:
            contracted.append(seq[i])
            i += 1

    return sign, tuple(contracted)


# ── 3. Build Output Term Map ──────────────────────────────────────────────────

def output_terms():
    """
    Exhaustively compute all 4×4 = 16 blade products and group by output blade.

    Returns:
      dict: { output_blade → [(sign, a_blade, b_blade), ...] }
    """
    result = {blade: [] for blade in BLADES}
    for a in BLADES:
        for b in BLADES:
            sign, out = blade_product(a, b)
            result[out].append((sign, a, b))
    return result


# ── 4. Verilog Emitter ────────────────────────────────────────────────────────

def emit_verilog(module="geometric_product_cl20", in_bits=8, out_bits=18):
    """
    Emit a Verilog module string for the Cl(2,0) geometric product C = A * B.

    Args:
      module   : Verilog module name
      in_bits  : bit-width of signed inputs  (default 8  → INT8)
      out_bits : bit-width of signed outputs (default 18 → safe accumulation)

    Returns:
      str : complete Verilog source
    """
    terms = output_terms()
    L     = BLADE_LABEL
    lines = []

    # ── Header ───────────────────────────────────────────────────────────────
    lines += [
        "// ─────────────────────────────────────────────────────────────────",
        "// Auto-generated by VerilogEmitter",
        f"// Algebra : Cl(2,0)  (2D Euclidean Geometric Algebra)",
        f"// Bases   : scalar(0), e1(1), e2(2), e12(12)",
        f"// Metric  : e1² = e2² = +1",
        f"// Inputs  : INT{in_bits} signed  →  Outputs : INT{out_bits} signed",
        "// Operation: C = A * B  (full geometric product)",
        "// ─────────────────────────────────────────────────────────────────",
        "",
        f"module {module} (",
    ]

    # ── Port declarations ─────────────────────────────────────────────────────
    all_ports = []
    for b in BLADES:
        all_ports.append(f"    input  signed [{in_bits - 1}:0] a{L[b]}")
    for b in BLADES:
        all_ports.append(f"    input  signed [{in_bits - 1}:0] b{L[b]}")
    for b in BLADES:
        all_ports.append(f"    output signed [{out_bits - 1}:0] c{L[b]}")

    lines.append(",\n".join(all_ports))
    lines += ["", ");", ""]

    # ── Assign statements (one per output blade) ──────────────────────────────
    for blade in BLADES:
        lbl        = L[blade]
        blade_terms = terms[blade]

        # Build expression string
        expr_parts = []
        for i, (sign, a_blade, b_blade) in enumerate(blade_terms):
            al, bl = L[a_blade], L[b_blade]
            mul    = f"(a{al} * b{bl})"
            if i == 0:
                # First term: no leading operator (use unary minus if negative)
                expr_parts.append(f"-{mul}" if sign == -1 else mul)
            else:
                op = "+" if sign == 1 else "-"
                expr_parts.append(f"{op} {mul}")

        expr = " ".join(expr_parts)

        lines += [
            f"    // {BLADE_NAME[blade]}",
            f"    assign c{lbl} = {expr};",
            "",
        ]

    lines.append("endmodule")
    return "\n".join(lines)


# ── 5. Diagnostic: Print Cayley Table ────────────────────────────────────────

def print_cayley_table():
    """Pretty-print the Cl(2,0) Cayley table for verification."""
    L = BLADE_LABEL

    def fmt(sign, blade):
        prefix = "-" if sign == -1 else " "
        b_str  = "1" if not blade else "e" + "".join(str(i) for i in blade)
        return f"{prefix}{b_str}"

    col_w  = 8
    header = f"{'*':>{col_w}}" + "".join(
        f"{'e' + ''.join(str(i) for i in b) if b else '1':>{col_w}}"
        for b in BLADES
    )
    print("\nCl(2,0) Cayley Table")
    print("─" * len(header))
    print(header)
    print("─" * len(header))
    for a in BLADES:
        row_label = "e" + "".join(str(i) for i in a) if a else "1"
        row = f"{row_label:>{col_w}}"
        for b in BLADES:
            sign, result = blade_product(a, b)
            row += f"{fmt(sign, result):>{col_w}}"
        print(row)
    print()


# ── 6. Main ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Show the Cayley table so you can verify the algebra is correct
    print_cayley_table()

    # Generate Verilog
    verilog = emit_verilog(
        module   = "geometric_product_cl20",
        in_bits  = 8,
        out_bits = 18,
    )

    # Print to console
    print(verilog)

    # Save to file
    fname = "geometric_product_cl20.v"
    with open(fname, "w") as f:
        f.write(verilog)

    print(f"\n// ✓ Saved → {fname}")
    print("// Next: simulate with  →  iverilog -o sim geometric_product_cl20.v testbench.v && vvp sim")
